<?php
/**
 * @file
 * RSVP Module hooks.
 */
use Drupal\Core\Form\FormStateInterface;
/**
* Implements hook_form_alter().
 *
* Alter the node add/edit form to include admin setting for displaying RSVPBlock with content
*/
function rsvplist_tool_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  $current_node_type = $node->getType();
  $config = \Drupal::config('rsvplist_tool.settings');
  $types = $config->get('allowed_types', array());
// RSVP Options for administrators
  if (in_array($current_node_type, $types)){
  $form['rsvplist_tool'] = array(
    '#type' => 'details',
    '#title' => t('RSVP Collection'),
    '#access' => \Drupal::currentUser()->hasPermission('administer rsvplist_tool'),
    '#group' => 'advanced',
    '#weight' => 100,
  );
    /** @var \Drupal\rsvplist_tool\EnablerService $enabler */
    $enabler = \Drupal::service('rsvplist_tool.enabler');
  $form['rsvplist_tool']['rsvplist_tool_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Collect RSVP e-mail addresses for this node.'),
    '#default_value' => $enabler->isEnabled($node),
  );
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]
    ['#type'] === 'submit') {
    $form['actions'][$action]['#submit'][] = 'rsvplist_tool_form_node_form_submit';
    }
  }
  }
}
/**
 * Form submission handler for RSVP item field on the node form.
 *
 * @see rsvplist_tool_form_node_form_alter()
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function rsvplist_tool_form_node_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\rsvplist_tool\EnablerService $enabler */
  $enabler = \Drupal::service('rsvplist_tool.enabler');
  $node = $form_state->getFormObject()->getEntity();
  if ($enabled = $form_state->getValue('rsvplist_tool_enabled')) {
    $enabler->setEnabled($node);
  }
  else {
    $enabler->delEnabled($node);
  }
}
